// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotenVonSchuelernFuerLehrer.Domain.Model;

#nullable disable

namespace NotenVonSchuelernFuerLehrer.Domain.Model.Migrations
{
    [DbContext(typeof(NotenVonSchuelernFuerLehrerDbContext))]
    [Migration("20251207221940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KlasseFach", b =>
                {
                    b.Property<Guid>("KlasseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FachId")
                        .HasColumnType("char(36)");

                    b.HasKey("KlasseId", "FachId")
                        .HasName("PK_KlasseFach");

                    b.HasIndex("FachId");

                    b.ToTable("KlasseFach", (string)null);
                });

            modelBuilder.Entity("LehrerFach", b =>
                {
                    b.Property<Guid>("LehrerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FachId")
                        .HasColumnType("char(36)");

                    b.HasKey("LehrerId", "FachId")
                        .HasName("PK_LehrerFach");

                    b.HasIndex("FachId");

                    b.ToTable("LehrerFach", (string)null);
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Fach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Kurzbezeichnung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Fach");

                    b.ToTable("Fach");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Klasse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Kurzbezeichnung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Klasse");

                    b.ToTable("Klasse");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Lehrer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("BildByteArray")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Lehrer");

                    b.ToTable("Lehrer");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AngepasstAm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FachId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SchuelerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Wert")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Note");

                    b.HasIndex("FachId");

                    b.HasIndex("SchuelerId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Schueler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("BildByteArray")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<Guid>("KlasseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Schueler");

                    b.HasIndex("KlasseId");

                    b.ToTable("Schueler");
                });

            modelBuilder.Entity("KlasseFach", b =>
                {
                    b.HasOne("NotenVonSchuelernFuerLehrer.Domain.Model.Fach", null)
                        .WithMany()
                        .HasForeignKey("FachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KlasseFach_Fach");

                    b.HasOne("NotenVonSchuelernFuerLehrer.Domain.Model.Klasse", null)
                        .WithMany()
                        .HasForeignKey("KlasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KlasseFach_Klasse");
                });

            modelBuilder.Entity("LehrerFach", b =>
                {
                    b.HasOne("NotenVonSchuelernFuerLehrer.Domain.Model.Fach", null)
                        .WithMany()
                        .HasForeignKey("FachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LehrerFach_Fach");

                    b.HasOne("NotenVonSchuelernFuerLehrer.Domain.Model.Lehrer", null)
                        .WithMany()
                        .HasForeignKey("LehrerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LehrerFach_Lehrer");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Note", b =>
                {
                    b.HasOne("NotenVonSchuelernFuerLehrer.Domain.Model.Fach", "Fach")
                        .WithMany("Noten")
                        .HasForeignKey("FachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Note_Fach");

                    b.HasOne("NotenVonSchuelernFuerLehrer.Domain.Model.Schueler", "Schueler")
                        .WithMany("Noten")
                        .HasForeignKey("SchuelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Note_Schueler");

                    b.Navigation("Fach");

                    b.Navigation("Schueler");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Schueler", b =>
                {
                    b.HasOne("NotenVonSchuelernFuerLehrer.Domain.Model.Klasse", "Klasse")
                        .WithMany("Schueler")
                        .HasForeignKey("KlasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Schueler_Klasse");

                    b.Navigation("Klasse");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Fach", b =>
                {
                    b.Navigation("Noten");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Klasse", b =>
                {
                    b.Navigation("Schueler");
                });

            modelBuilder.Entity("NotenVonSchuelernFuerLehrer.Domain.Model.Schueler", b =>
                {
                    b.Navigation("Noten");
                });
#pragma warning restore 612, 618
        }
    }
}
